import { Audience, Service } from "@/app/laundry/page";

type LaundryRow = {
  id: string;
  audience: Audience;
  service: Service;
  item: string;
  price: number;
};

export const laundryRows: LaundryRow[] = [
  {
    id: "gents-laundry-shirt-long-sleeve",
    audience: "Gents",
    service: "Laundry",
    item: "Shirt (Long Sleeve)",
    price: 3500,
  },
  {
    id: "gents-laundry-shirt-short-sleeve",
    audience: "Gents",
    service: "Laundry",
    item: "Shirt (Short Sleeve)",
    price: 3000,
  },
  {
    id: "gents-laundry-under-shirt",
    audience: "Gents",
    service: "Laundry",
    item: "Under Shirt",
    price: 2000,
  },
  {
    id: "gents-laundry-under-short",
    audience: "Gents",
    service: "Laundry",
    item: "Under Short",
    price: 2000,
  },
  {
    id: "gents-laundry-pyjamas",
    audience: "Gents",
    service: "Laundry",
    item: "Pyjamas",
    price: 3000,
  },
  {
    id: "gents-laundry-socks",
    audience: "Gents",
    service: "Laundry",
    item: "Socks",
    price: 2000,
  },
  {
    id: "gents-laundry-handkerchief",
    audience: "Gents",
    service: "Laundry",
    item: "Handkerchief",
    price: 2000,
  },
  {
    id: "gents-laundry-trouser",
    audience: "Gents",
    service: "Laundry",
    item: "Trouser",
    price: 3000,
  },
  {
    id: "gents-laundry-suit",
    audience: "Gents",
    service: "Laundry",
    item: "Suit",
    price: 5000,
  },
  {
    id: "gents-laundry-jacket",
    audience: "Gents",
    service: "Laundry",
    item: "Jacket",
    price: 5000,
  },
  {
    id: "gents-laundry-bathrobe",
    audience: "Gents",
    service: "Laundry",
    item: "Bathrobe",
    price: 3000,
  },
  {
    id: "gents-laundry-short",
    audience: "Gents",
    service: "Laundry",
    item: "Short",
    price: 3000,
  },
  {
    id: "gents-laundry-tshirt",
    audience: "Gents",
    service: "Laundry",
    item: "T-Shirt",
    price: 2500,
  },
  {
    id: "gents-laundry-jean",
    audience: "Gents",
    service: "Laundry",
    item: "Jean",
    price: 3000,
  },
  {
    id: "gents-laundry-kaftan",
    audience: "Gents",
    service: "Laundry",
    item: "Kaftan",
    price: 4000,
  },
  {
    id: "gents-laundry-agbada",
    audience: "Gents",
    service: "Laundry",
    item: "Agbada",
    price: 5000,
  },
  {
    id: "gents-laundry-jalabiya",
    audience: "Gents",
    service: "Laundry",
    item: "Jalabiya",
    price: 4000,
  },
  {
    id: "gents-laundry-sweater",
    audience: "Gents",
    service: "Laundry",
    item: "Sweater",
    price: 3000,
  },
  {
    id: "gents-laundry-shoes",
    audience: "Gents",
    service: "Laundry",
    item: "Shoes",
    price: 3000,
  },
  {
    id: "gents-dry-shirt",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Shirt",
    price: 3500,
  },
  {
    id: "gents-dry-under-shirt",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Under Shirt",
    price: 2000,
  },
  {
    id: "gents-dry-under-short",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Under Short",
    price: 2000,
  },
  {
    id: "gents-dry-pyjamas",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Pyjamas",
    price: 3000,
  },
  {
    id: "gents-dry-socks",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Socks",
    price: 2000,
  },
  {
    id: "gents-dry-handkerchief",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Handkerchief",
    price: 2000,
  },
  {
    id: "gents-dry-trouser-jean",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Trouser / Jean",
    price: 3000,
  },
  {
    id: "gents-dry-suit",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Suit",
    price: 5000,
  },
  {
    id: "gents-dry-jacket",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Jacket",
    price: 5000,
  },
  {
    id: "gents-dry-bathrobe",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Bathrobe",
    price: 3000,
  },
  {
    id: "gents-dry-short",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Short",
    price: 3000,
  },
  {
    id: "gents-dry-tshirt",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "T-Shirt",
    price: 2500,
  },
  {
    id: "gents-dry-kaftan",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Kaftan",
    price: 4000,
  },
  {
    id: "gents-dry-agbada",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Agbada",
    price: 5000,
  },
  {
    id: "gents-dry-jalabiya",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Jalabiya",
    price: 4000,
  },
  {
    id: "gents-dry-sweater",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Sweater",
    price: 3000,
  },
  {
    id: "gents-dry-tie",
    audience: "Gents",
    service: "Dry Cleaning",
    item: "Tie",
    price: 2000,
  },
  {
    id: "ladies-laundry-blouse",
    audience: "Ladies",
    service: "Laundry",
    item: "Blouse",
    price: 3000,
  },
  {
    id: "ladies-laundry-dress",
    audience: "Ladies",
    service: "Laundry",
    item: "Dress",
    price: 4000,
  },
  {
    id: "ladies-laundry-skirt",
    audience: "Ladies",
    service: "Laundry",
    item: "Skirt",
    price: 3000,
  },
  {
    id: "ladies-laundry-silk-dress",
    audience: "Ladies",
    service: "Laundry",
    item: "Silk Dress",
    price: 3000,
  },
  {
    id: "ladies-laundry-shorts",
    audience: "Ladies",
    service: "Laundry",
    item: "Shorts",
    price: 2500,
  },
  {
    id: "ladies-laundry-trouser-jeans",
    audience: "Ladies",
    service: "Laundry",
    item: "Trouser / Jeans",
    price: 3000,
  },
  {
    id: "ladies-laundry-sweater",
    audience: "Ladies",
    service: "Laundry",
    item: "Sweater",
    price: 3000,
  },
  {
    id: "ladies-laundry-nightgown",
    audience: "Ladies",
    service: "Laundry",
    item: "Nightgown",
    price: 3000,
  },
  {
    id: "ladies-laundry-pyjamas",
    audience: "Ladies",
    service: "Laundry",
    item: "Pyjamas",
    price: 2500,
  },
  {
    id: "ladies-laundry-panty",
    audience: "Ladies",
    service: "Laundry",
    item: "Panty",
    price: 2500,
  },
  {
    id: "ladies-laundry-brassier",
    audience: "Ladies",
    service: "Laundry",
    item: "Brassier",
    price: 2500,
  },
  {
    id: "ladies-laundry-swimsuit",
    audience: "Ladies",
    service: "Laundry",
    item: "Swimsuit",
    price: 2500,
  },
  {
    id: "ladies-laundry-scarf",
    audience: "Ladies",
    service: "Laundry",
    item: "Scarf",
    price: 2500,
  },
  {
    id: "ladies-laundry-socks",
    audience: "Ladies",
    service: "Laundry",
    item: "Socks",
    price: 2500,
  },
  {
    id: "ladies-laundry-evening-dress",
    audience: "Ladies",
    service: "Laundry",
    item: "Evening Dress",
    price: 3000,
  },
  {
    id: "ladies-laundry-suit",
    audience: "Ladies",
    service: "Laundry",
    item: "Suit",
    price: 5000,
  },
  {
    id: "ladies-laundry-coat",
    audience: "Ladies",
    service: "Laundry",
    item: "Coat",
    price: 5000,
  },
  {
    id: "ladies-laundry-jacket",
    audience: "Ladies",
    service: "Laundry",
    item: "Jacket",
    price: 5000,
  },
  {
    id: "ladies-laundry-boubou",
    audience: "Ladies",
    service: "Laundry",
    item: "BouBou",
    price: 3500,
  },
  {
    id: "ladies-laundry-wrapper",
    audience: "Ladies",
    service: "Laundry",
    item: "Wrapper",
    price: 3000,
  },
  {
    id: "ladies-dry-blouse",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Blouse",
    price: 3000,
  },
  {
    id: "ladies-dry-dress",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Dress",
    price: 4000,
  },
  {
    id: "ladies-dry-skirt",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Skirt",
    price: 3000,
  },
  {
    id: "ladies-dry-silk-dress",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Silk Dress",
    price: 3000,
  },
  {
    id: "ladies-dry-shorts",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Shorts",
    price: 2500,
  },
  {
    id: "ladies-dry-trouser-jeans",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Trouser / Jeans",
    price: 3000,
  },
  {
    id: "ladies-dry-sweater",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Sweater",
    price: 3000,
  },
  {
    id: "ladies-dry-nightgown",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Nightgown",
    price: 3000,
  },
  {
    id: "ladies-dry-pyjamas",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Pyjamas",
    price: 2500,
  },
  {
    id: "ladies-dry-panty",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Panty",
    price: 2500,
  },
  {
    id: "ladies-dry-scarf",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Scarf",
    price: 2500,
  },
  {
    id: "ladies-dry-socks",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Socks",
    price: 2500,
  },
  {
    id: "ladies-dry-evening-dress",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Evening Dress",
    price: 3000,
  },
  {
    id: "ladies-dry-suit",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Suit",
    price: 5000,
  },
  {
    id: "ladies-dry-coat",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Coat",
    price: 5300,
  },
  {
    id: "ladies-dry-jacket",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Jacket",
    price: 5000,
  },
  {
    id: "ladies-dry-boubou",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "BouBou",
    price: 3500,
  },
  {
    id: "ladies-dry-wrapper",
    audience: "Ladies",
    service: "Dry Cleaning",
    item: "Wrapper",
    price: 3000,
  },
];